### ISSUE TITLE
Sky flickers on large maps

### ISSUE THREAD

**Issue by ghost** [looterz/atmos#1]
Originally thought this was caused by the code itself, but I think it's related to https://github.com/Facepunch/garrysmod-issues/issues/5327

Any pointers? I have no idea what could be causing this.

Affected maps:
- gm_wangan
- rp_unioncity
- rp_southside
- rp_nycity

**Comment by looterz** [comment]
This issue sounds familiar but its been years, does it happen on Atmos v1 on the workshop? I remember having to do some hacky workarounds to fix issues like this.

**Comment by ghost** [comment]
> This issue sounds familiar but its been years, does it happen on Atmos v1 on the workshop? I remember having to do some hacky workarounds to fix issues like this.

For the maps that this issue happens on ([rp_nycity](https://steamcommunity.com/sharedfiles/filedetails/?id=2925489145), [rp_southside](https://steamcommunity.com/sharedfiles/filedetails/?id=2010286798), [rp_unioncity](https://steamcommunity.com/sharedfiles/filedetails/?id=1656078410)), I couldn't reproduce this issue on rp_unioncity or rp_southside when using Atmos v1 but I never tried rp_nycity in v1. There could be more maps that are affected by this but in the others that I've tested (gm_fork, gm_flatgrass, gm_construct, rp_truenorth, rp_evocity) I didn't notice issues on any of those.

It also happens on [gm_edge](https://steamcommunity.com/sharedfiles/filedetails/?id=2143662013), but I haven't tested that one with Atmos v1 and it's probably caused by https://github.com/Facepunch/garrysmod-issues/issues/5327.

**Comment by looterz** [comment]
4b1c80985044e087678f372f4204fd4e2aa7bd17 Might fix issues for some maps, but maps like `rp_unioncity` that have custom skyboxes have to get custom support, usually this means figuring out what they've named those entities and deleting them during `InitPostEntity`, this is what I do for Evocity in the addon already but each map is different, and these days there seem to be dozens of custom evocity's and I'm sure some of them have renamed `daynight_brush` to something else.

That's my guess anyway, it was common with TF2 maps as well. Could be an engine/shader related issue too.

**Comment by ghost** [comment]
> [4b1c809](https://github.com/looterz/atmos/commit/4b1c80985044e087678f372f4204fd4e2aa7bd17) Might fix issues for some maps, but maps like `rp_unioncity` that have custom skyboxes have to get custom support, usually this means figuring out what they've named those entities and deleting them during `InitPostEntity`, this is what I do for Evocity in the addon already but each map is different, and these days there seem to be dozens of custom evocity's and I'm sure some of them have renamed `daynight_brush` to something else.
> 
> That's my guess anyway, it was common with TF2 maps as well. Could be an engine/shader related issue too.

Here is the complete ``ents.GetAll`` print of rp_nycity: https://pastebin.com/fDTAsmkH

None of the entity classes piqued me as suspicious, so I hoped BSPSpy would reveal more info on rp_unioncity but it didn't besides MAYBE suggesting [sky_camera](https://developer.valvesoftware.com/wiki/Sky_camera) as the cause. r_3dsky 0 doesn't fix the issue, so I don't think sky_camera is the cause. I'm stumped at this point besides it likely being a problem with Atmos' code.

**Comment by ghost** [comment]
ok this might be fixed now: https://github.com/Facepunch/garrysmod-issues/issues/5327#issuecomment-1825742070

the linked issue was caused due to env_skypaint flickering when not given a valid sun normal. i see some weird things in both the UpdateSkybox and UpdateSun functions (eg: https://github.com/looterz/atmos/blob/master/lua/atmos/shared/sh_sky.lua#L438) so there's a good chance the above fixed this
