### ISSUE TITLE
Moon is stretched

### ISSUE THREAD

**Issue by ghost** [looterz/atmos#2]
Relevant code here: https://github.com/looterz/atmos/blob/master/lua/atmos/shared/sh_sky.lua#L489

Can be seen in this screenshot:
![gmod 2023-04-09 22-32-48](https://github.com/looterz/atmos/assets/43250660/48d2f824-8309-4a2f-a4ca-daac8524bc60)

Something to do with the positions/angles, difficult to debug because I don't know how to reinitialize the skyclass without restarting the entire server.

**Comment by looterz** [comment]
Destroying and re-creating atmos_sky and other relevant stuff we do during init when a reload is detected should do the trick i think
