### ISSUE TITLE
game.CleanUpMap deletes Atmos entities

### ISSUE THREAD

**Issue by ghost** [looterz/atmos#3]
Fixed by using [Entity:AddEFlags](https://wiki.facepunch.com/gmod/Entity:AddEFlags) to add the [EFL_KEEP_ON_RECREATE_ENTITIES](https://wiki.facepunch.com/gmod/enums/EFL#EFL_KEEP_ON_RECREATE_ENTITIES) flag when Atmos entities are initialized.

**Comment by looterz** [comment]
Can you submit a PR with this change?

**Comment by ghost** [comment]
> Can you submit a PR with this change?

yeah, it's at #5

**Comment by looterz** [comment]
Awesome, thanks
